# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push]

jobs:
  build:

    environment: DEV
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run hello world
      with:
        FIRST_NAME = "Pallav"
      run:
        echo hello world $FIRST_NAME
    - name: Run hello world
      with:
        FIRST_NAME = "Pallav"
      run:
        echo hello world $FIRST_NAME
    - name: Test with pytest
      uses: SpicyPizza/create-envfile@v1
      with:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE: ${{ secrets.NOTION_DATABASE }}
      run: |
        pytest